tasks:
  build-image:
    runner: razorci/img
    steps:
    - checkout
    - docker/build:
        image: docker.pkg.github.com/kshyam/go-static-site/demo
        dockerfile: Dockerfile.build
        push: true

  build-image-vm:
    runner:
      os_image: ubuntu
    steps:
    - checkout
    - docker/build:
        image: docker.pkg.github.com/kshyam/go-static-site/demo
        dockerfile: Dockerfile.build
        push: true
        tags: [latest_v1]
