tasks:
  build-image:
    runner: razorci/golang
    steps:
    - docker/build:
      image: github.com/kshyam/go-static-site
      dockerfile: Dockerfile
    - docker/push:
      image: github.com/kshyam/go-static-site
