global:
  runner: razorci/golang

tasks:
  build-image:
    steps:
    - run: git --version
    - docker/build:
      image: github.com/kshyam/go-static-site
      tags: [latest,v1]
      dockerfile: Dockerfile
    - docker/push:
      image: github.com/kshyam/go-static-site
      tags: [latest,v1]
